s=set()
n=input("Enter A Number : ")
s.add(int(n))
n=input("Enter A Number : ")
s.add(int(n))
n=input("Enter A Number : ")
s.add(int(n))
n=input("Enter A Number : ")
s.add(int(n))
n=input("Enter A Number : ")
s.add(int(n))
n=input("Enter A Number : ")
s.add(int(n))
n=input("Enter A Number : ")
s.add(int(n))

print(s)