fruits=[]
f1=input("Enter The First Number : ")
fruits.append(f1)
f2=input("Enter The Second Number : ")
fruits.append(f2)
f3=input("Enter The Third Number : ")
fruits.append(f3)
f4=input("Enter The Fourth Number : ")
fruits.append(f4)
f5=input("Enter The Fifth umber : ")
fruits.append(f5)
f6=input("Enter The Sixth Number : ")
fruits.append(f6)
f7=input("Enter The Seventh Number : ")
fruits.append(f7)

print(fruits)